---
booktitle: Proceedings of the The 39th Canadian Conference on Artificial Intelligence
shortname: CAI
year: '2026'
volume: '318'
start: &1 2026-05-25
end: 2026-05-29
published: 2026-06-29
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: canadianai26
month: 0
cycles: false
bibtex_editor: Bouzar-Benlabiod, Lydia and Leung, Carson
editor:
- given: Lydia
  family: Bouzar-Benlabiod
- given: Carson
  family: Leung
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the The 39th Canadian Conference on Artificial Intelligence
    Held in Simon Fraser University, Burnaby, British Columbia, Canada. on 25-29 May 2026

  Published as Volume 318 by the Proceedings of Machine Learning Research on 29 June 2026.

  Volume Edited by:
    Lydia Bouzar-Benlabiod
    Carson Leung

  Series Editors:
    Neil D. Lawrence
date_str: 25--29 May
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v318"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v318
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v318
email: ''
conference:
  name: The 39th Canadian Conference on Artificial Intelligence
  url: https://www.caiac.ca/en/conferences/canadianai-2026/home
  location: Simon Fraser University, Burnaby, British Columbia, Canada.
  dates:
  - *1
  - 2026-05-26
  - 2026-05-27
  - 2026-05-28
  - 2026-05-29
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: Bibtex_clean.bib
# Site settings
# Original source:  Bibtex_clean.bib
